### ISSUE TITLE
Nuget Package Availablity

### ISSUE THREAD

**Issue by muhamad-ahsan** [JonPSmith/MvcUsingBower#1]
Hi, is there any chance to get it through nuget? or bower?... Coz in a current situation is not easy to use....

**Comment by JonPSmith** [comment]
Hi @ muhamadahsan,

Sorry, I know I should do that but I haven't got round to it. Creating a good NuGet with the different .NET flavours is hard work and I'm not quite sure on the best way to do it. If you have any links to good examples of how to build a multi .Net version NuGet then let me know. 

PS. I use it by compiling MvcUsingBower in release mode and linking in the built B4BCore.dll into my app using "Add Reference->Browse". Then I copy in the single file [BowerBundlerHelper](https://github.com/JonPSmith/MvcUsingBower/blob/master/WebApplication.Mvc5/App_Start/BowerBundlerHelper.cs) into my app.

**Comment by JonPSmith** [comment]
Hi @muhamadahsan,

I have released this project on Nuget as [Bundler4Bower](https://www.nuget.org/packages/Bundler4Bower/). I needed it for a client project. It is only targeted at .NET4.5.1 as .NET Core has its own, similar solution through the [Bundler & Minifier](https://github.com/madskristensen/BundlerMinifier).

Note that NuGet package does not copy over the [BowerBundlerHelper](https://github.com/JonPSmith/MvcUsingBower/blob/master/WebApplication.Mvc5/App_Start/BowerBundlerHelper.cs) or any other the other files because you can install it in Unit Tests and those files would be inappropriate. However, when you install the package it does give you a list of the files you need to copy.

I hope this is helpful to you.

**Comment by muhamad-ahsan** [comment]
@JonPSmith: Thanks dear for the request completion... 👍. I am not sure that at this moment I can utilize this; but maybe in future or recommendation.
